name: silica
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rust=1.97.1
  - pkg-config
  - capstone=5.0.9
  - llvmdev=22.1.8
  - llvm-tools=22.1.8
  - binutils
  - unicorn=2.1.2
  - openjdk=21
  - lxml
  - numpy
  - pyyaml
  - typer
  - zstandard
  - pytest
  - hypothesis
  - ruff
  - mypy
  - make
  - pip
  - pip:
      - -e .[dev]
      - types-PyYAML
